language: python
python:
- '3.4'
- '3.5'
- '3.6'
- pypy
install: pip install -e .[test]
script: python setup.py test
env:
  global:
    secure: Ow1xymFSpsvVTEZnfrngdwf7hyTapHbLhTR6IvQOLwWxiWLxp/+j4Lv+bVZTzKio2ybc52YpTOM/q3cUL4Wx8EwjVoou78NPX4y0jT0R2ZjmjZUhFWA7G63fwr9TDQHMlGJ0MPObXcY05sTfme3DmSh7zjsS0iY2ZZhbPkMbp6ncnOVC9Q5Bd+4sgSwqoSk+ZHHgTlCDfpoEDwNQBqzrMhjv/8zCYTO30oB4JfAjOpVcDSQpdAh3e4lD0aGjuH4p0goIxTnUDPuZ3CqdiQvjMl46jXc7oI1UqRi0ltt1+4tw3V6GM0C/frDjV3GlRhtGhVHsyfd9fHBq6yqZ0Z67knUhwhLARdpbjR1qVREAzt+leo5WBYm051zHJ+niR9//kp+7SCMDWvAfD7kyJT2qsvT9M3Tu5sVtlxGstk8u2EN0XI1P2/beYQxZcjpPh58CtorAptlB0MPAGy89pusK+l7NjBeeRGOHwZKDZqNBO0JVsJwQMB7FuO3njjcnms8p0Bc1LGv0DjDeWvExJINRvSLryCZ0Oe9UxLbPIO1R3KV1+Imt1lxYPYlMT4TMucaPeTAKoHaPIcAft3RBVvOAEmpK/hXFnxGkjcbRkakHXcadNy2BKvMpXBrwU07Kr5VjCDR2KSpegLt4cUvCPsnhskjMRzT4jwgIh+4OaLMEtSY=
